my_dbt_project:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ../data/marketing.duckdb
      extensions:
        - httpfs
      settings:
        s3_endpoint: localhost:9000
        s3_access_key_id: minio_admin
        s3_secret_access_key: minio_password
        s3_use_ssl: false
        s3_url_style: path